name: Generate Stats Images

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at midnight
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=zakattack02&show_icons=true&theme=tokyonight'
          path: profile/stats.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate Language Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=zakattack02&layout=compact&theme=tokyonight&langs_count=5'
          path: profile/top-langs.svg
          token: ${{ secrets.GH_PAT }}

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update stats images" || exit 0
          git push